name: build

on:
  push:
    paths-ignore:
      - "**.md"
      - LICENSE
      - .github/FUNDING.yml
    branches: [main, dev]
  pull_request:
    paths-ignore:
      - "**.md"
      - LICENSE
      - .github/FUNDING.yml
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Installing pip dependencies
        run: python -m pip install --upgrade pip clickgen
        continue-on-error: false

      # https://github.com/returntocorp/semgrep/issues/4794
      - name: Fixing 'attr' module error
        run: pip install --force-reinstall --upgrade attrs

      - name: Building `GoogleDot Blue` Cursors
        run: ctgen build.toml -d 'bitmaps/GoogleDot-Blue' -n 'GoogleDot-Blue' -c 'Blue cursor theme inspired on Google'

      - name: Building `GoogleDot White` Cursors
        run: ctgen build.toml -d 'bitmaps/GoogleDot-White' -n 'GoogleDot-White' -c 'White cursor theme inspired on Google'

      - name: Building `GoogleDot Black` Cursors
        run: ctgen build.toml -d 'bitmaps/GoogleDot-Black' -n 'GoogleDot-Black' -c 'Black cursor theme inspired on Google'

      - name: Building `GoogleDot Red` Cursors
        run: ctgen build.toml -d 'bitmaps/GoogleDot-Red' -n 'GoogleDot-Red' -c 'Red cursor theme inspired on Google'

      - name: Building `GoogleDot Green` Cursors
        run: ctgen build.toml -d 'bitmaps/GoogleDot-Green' -n 'GoogleDot-Green' -c 'Green cursor theme inspired on Google'
